ISPP-Eventbride/Eventbride-documentation

docs/S2/changelogDoc.md
=> Changelog (DOC)

docs/AIusage.md
Addition of some conversations #256
=> AIusage (DOC)

docs/S2/timeEffortReport.md
=> timeEffortReport (DOC)

docs/S1/pilotUsers.md, docs/S1/pilotUsersPerformanceEvaluation.md, docs/S2/pilotUsers.md, docs/S2/pilotUsersPerformanceEvaluation.md
the doc has been pasted in the S2 folder
=> pilotUsers added to S2 folder (DOC)

docs/S2/Commitment Agreement usuarios piloto/pilotUsersCommitmentAgreement-Albramvar1.md, docs/S2/Commitment Agreement usuarios piloto/pilotUsersCommitmentAgreement-Felsolagu.md, docs/S2/Commitment Agreement usuarios piloto/pilotUsersCommitmentAgreement-hugborang.md, docs/S2/Commitment Agreement usuarios piloto/pilotUsersCommitmentAgreement-ramvergar.md, docs/S2/Commitment Agreement usuarios piloto/pilotUsersCommitmentAgreement.md
updated the pilotUsersCommitmentAgreemint to introduce the eval method.
=> pilotUserCommitmentAgreement (DOC)

docs/S3/GuionInversores.md
=> guion inversores (DOC)

docs/S3/planDePruebas.md, docs/S3/testingPlan.md
testing plan done #341
Este documento va a ser editado conforme se vayan haciendo los tests
=> Plan de pruebas (DOC)

docs/S3/analisisEquipo-CharterGoal.md, docs/S3/teamCoordinationAndCharterGoal.md
Details the new team composition, skills, preliminary structure, and charter goal for the EventBride project. #328
=> Team Coordination and Charter Goal (DOC)

docs/S3/appMonetization.md, docs/S3/costsAnalysis.md
=> Cost Analysis (DOC)

docs/S3/requirements.md
Tarea realizada junto a Manuel Pérez
=> Update requierements (DOC)

docs/S3/Commitment agreement/commitmentAgreement-adrcabmar-v6.md, docs/S3/Commitment agreement/commitmentAgreement-andpizcer-v6.md, docs/S3/Commitment agreement/commitmentAgreement-antmonlop4-v6.md, docs/S3/Commitment agreement/commitmentAgreement-danbenhid-v6.md, docs/S3/Commitment agreement/commitmentAgreement-davgodfer-v6.md, docs/S3/Commitment agreement/commitmentAgreement-ferdehur-v6.md, docs/S3/Commitment agreement/commitmentAgreement-fraavicar1-v6.md, docs/S3/Commitment agreement/commitmentAgreement-gonnavrem-v6.md, docs/S3/Commitment agreement/commitmentAgreement-hecnoggon-v6.md, docs/S3/Commitment agreement/commitmentAgreement-ignblabla-v6.md, docs/S3/Commitment agreement/commitmentAgreement-lortorlan1-v6.md, docs/S3/Commitment agreement/commitmentAgreement-manpervel2-v6.md, docs/S3/Commitment agreement/commitmentAgreement-marcartal1-v6.md, docs/S3/Commitment agreement/commitmentAgreement-mighersan1-v6.md, docs/S3/Commitment agreement/commitmentAgreement-natolmvil-v6.md, docs/S3/Commitment agreement/commitmentAgreement-pabcascom-v6.md, docs/S3/Commitment agreement/commitmentAgreement-serponlop-v6.md, docs/S3/Commitment agreement/commitmentAgreement.md
=> Actualizar commitment agreement (DOC)

docs/S3/changelogDoc.md
=> Actualizar changelog (DOC)

docs/S3/KBReport.md
=> KBReport (DOC)

docs/S3/performanceEvaluation.md
The documment includes the evaluation of every team member and a text which describes their performance at this sprint. #308
=> Performance Evaluation (DOC)

docs/S3/testingPlan.md
=> testing plan (DOC)

docs/S3/revision.md
Added a new section titled "Any User" to the S3 revision documentation to include instructions for contacting customer support and managing notifications. This update ensures all user types are covered in the guide.
=> Revision (DOC)

eventbride/docs/PPL/KBReport.md
=> Documento: KB Report (DOC)

eventbride/docs/AIusage.md
documento de uso de ia completado #526
=> Alucinaciones de la IA (DOC)

eventbride/docs/PPL/TimeEffortReport.md
time effort report ppl done #501
=> Time Effort Report (DOC)

eventbride/docs/PPL/useCases.md
=> Casos de uso (DOC)

eventbride/docs/WPL/marketing_stats.md
=> Analizar estadísticas del marketing (DOCS)

eventbride/docs/WPL/costsAnalysis.md
=> Costs Analysis Half Sprint (DOC)

eventbride/docs/WPL/KBReport.md
=> KB Report (DOC)
